---
name: Renovate automerge

"on":
  pull_request_target: {}

jobs:
  automerge:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@524680520b97d41da35f7062e18ac6514b88fc7f  # master
    permissions:
      pull-requests: write
      contents: write
