---
name: Validate

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preset:
    name: Renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca  # v5.1.1
      - name: Validate preset
        run: mise run check

  lint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-general.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0
