---
name: Validate

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preset:
    name: Renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up mise
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5  # v5.0.0
      - name: Validate preset
        run: mise run check

  lint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-general.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1
